import type { ImageRequireSource } from 'react-native';

import { SYMBOL_COLORS } from '@/constants/faltchatt';

const markerImages: Record<string, ImageRequireSource[]> = {
  car: [
    require('../../assets/map-markers/car-c0.png'),
    require('../../assets/map-markers/car-c1.png'),
    require('../../assets/map-markers/car-c2.png'),
    require('../../assets/map-markers/car-c3.png'),
    require('../../assets/map-markers/car-c4.png'),
    require('../../assets/map-markers/car-c5.png'),
    require('../../assets/map-markers/car-c6.png'),
    require('../../assets/map-markers/car-c7.png'),
    require('../../assets/map-markers/car-c8.png'),
    require('../../assets/map-markers/car-c9.png'),
  ],
  hat: [
    require('../../assets/map-markers/hat-c0.png'),
    require('../../assets/map-markers/hat-c1.png'),
    require('../../assets/map-markers/hat-c2.png'),
    require('../../assets/map-markers/hat-c3.png'),
    require('../../assets/map-markers/hat-c4.png'),
    require('../../assets/map-markers/hat-c5.png'),
    require('../../assets/map-markers/hat-c6.png'),
    require('../../assets/map-markers/hat-c7.png'),
    require('../../assets/map-markers/hat-c8.png'),
    require('../../assets/map-markers/hat-c9.png'),
  ],
  heart: [
    require('../../assets/map-markers/heart-c0.png'),
    require('../../assets/map-markers/heart-c1.png'),
    require('../../assets/map-markers/heart-c2.png'),
    require('../../assets/map-markers/heart-c3.png'),
    require('../../assets/map-markers/heart-c4.png'),
    require('../../assets/map-markers/heart-c5.png'),
    require('../../assets/map-markers/heart-c6.png'),
    require('../../assets/map-markers/heart-c7.png'),
    require('../../assets/map-markers/heart-c8.png'),
    require('../../assets/map-markers/heart-c9.png'),
  ],
  leaf: [
    require('../../assets/map-markers/leaf-c0.png'),
    require('../../assets/map-markers/leaf-c1.png'),
    require('../../assets/map-markers/leaf-c2.png'),
    require('../../assets/map-markers/leaf-c3.png'),
    require('../../assets/map-markers/leaf-c4.png'),
    require('../../assets/map-markers/leaf-c5.png'),
    require('../../assets/map-markers/leaf-c6.png'),
    require('../../assets/map-markers/leaf-c7.png'),
    require('../../assets/map-markers/leaf-c8.png'),
    require('../../assets/map-markers/leaf-c9.png'),
  ],
  mushroom: [
    require('../../assets/map-markers/mushroom-c0.png'),
    require('../../assets/map-markers/mushroom-c1.png'),
    require('../../assets/map-markers/mushroom-c2.png'),
    require('../../assets/map-markers/mushroom-c3.png'),
    require('../../assets/map-markers/mushroom-c4.png'),
    require('../../assets/map-markers/mushroom-c5.png'),
    require('../../assets/map-markers/mushroom-c6.png'),
    require('../../assets/map-markers/mushroom-c7.png'),
    require('../../assets/map-markers/mushroom-c8.png'),
    require('../../assets/map-markers/mushroom-c9.png'),
  ],
  spade: [
    require('../../assets/map-markers/spade-c0.png'),
    require('../../assets/map-markers/spade-c1.png'),
    require('../../assets/map-markers/spade-c2.png'),
    require('../../assets/map-markers/spade-c3.png'),
    require('../../assets/map-markers/spade-c4.png'),
    require('../../assets/map-markers/spade-c5.png'),
    require('../../assets/map-markers/spade-c6.png'),
    require('../../assets/map-markers/spade-c7.png'),
    require('../../assets/map-markers/spade-c8.png'),
    require('../../assets/map-markers/spade-c9.png'),
  ],
  star: [
    require('../../assets/map-markers/star-c0.png'),
    require('../../assets/map-markers/star-c1.png'),
    require('../../assets/map-markers/star-c2.png'),
    require('../../assets/map-markers/star-c3.png'),
    require('../../assets/map-markers/star-c4.png'),
    require('../../assets/map-markers/star-c5.png'),
    require('../../assets/map-markers/star-c6.png'),
    require('../../assets/map-markers/star-c7.png'),
    require('../../assets/map-markers/star-c8.png'),
    require('../../assets/map-markers/star-c9.png'),
  ],
  train: [
    require('../../assets/map-markers/train-c0.png'),
    require('../../assets/map-markers/train-c1.png'),
    require('../../assets/map-markers/train-c2.png'),
    require('../../assets/map-markers/train-c3.png'),
    require('../../assets/map-markers/train-c4.png'),
    require('../../assets/map-markers/train-c5.png'),
    require('../../assets/map-markers/train-c6.png'),
    require('../../assets/map-markers/train-c7.png'),
    require('../../assets/map-markers/train-c8.png'),
    require('../../assets/map-markers/train-c9.png'),
  ],
  tree: [
    require('../../assets/map-markers/tree-c0.png'),
    require('../../assets/map-markers/tree-c1.png'),
    require('../../assets/map-markers/tree-c2.png'),
    require('../../assets/map-markers/tree-c3.png'),
    require('../../assets/map-markers/tree-c4.png'),
    require('../../assets/map-markers/tree-c5.png'),
    require('../../assets/map-markers/tree-c6.png'),
    require('../../assets/map-markers/tree-c7.png'),
    require('../../assets/map-markers/tree-c8.png'),
    require('../../assets/map-markers/tree-c9.png'),
  ],
};

const ownMarkerImages: Record<string, ImageRequireSource[]> = {
  car: [
    require('../../assets/map-markers/own-car-c0.png'),
    require('../../assets/map-markers/own-car-c1.png'),
    require('../../assets/map-markers/own-car-c2.png'),
    require('../../assets/map-markers/own-car-c3.png'),
    require('../../assets/map-markers/own-car-c4.png'),
    require('../../assets/map-markers/own-car-c5.png'),
    require('../../assets/map-markers/own-car-c6.png'),
    require('../../assets/map-markers/own-car-c7.png'),
    require('../../assets/map-markers/own-car-c8.png'),
    require('../../assets/map-markers/own-car-c9.png'),
  ],
  hat: [
    require('../../assets/map-markers/own-hat-c0.png'),
    require('../../assets/map-markers/own-hat-c1.png'),
    require('../../assets/map-markers/own-hat-c2.png'),
    require('../../assets/map-markers/own-hat-c3.png'),
    require('../../assets/map-markers/own-hat-c4.png'),
    require('../../assets/map-markers/own-hat-c5.png'),
    require('../../assets/map-markers/own-hat-c6.png'),
    require('../../assets/map-markers/own-hat-c7.png'),
    require('../../assets/map-markers/own-hat-c8.png'),
    require('../../assets/map-markers/own-hat-c9.png'),
  ],
  heart: [
    require('../../assets/map-markers/own-heart-c0.png'),
    require('../../assets/map-markers/own-heart-c1.png'),
    require('../../assets/map-markers/own-heart-c2.png'),
    require('../../assets/map-markers/own-heart-c3.png'),
    require('../../assets/map-markers/own-heart-c4.png'),
    require('../../assets/map-markers/own-heart-c5.png'),
    require('../../assets/map-markers/own-heart-c6.png'),
    require('../../assets/map-markers/own-heart-c7.png'),
    require('../../assets/map-markers/own-heart-c8.png'),
    require('../../assets/map-markers/own-heart-c9.png'),
  ],
  leaf: [
    require('../../assets/map-markers/own-leaf-c0.png'),
    require('../../assets/map-markers/own-leaf-c1.png'),
    require('../../assets/map-markers/own-leaf-c2.png'),
    require('../../assets/map-markers/own-leaf-c3.png'),
    require('../../assets/map-markers/own-leaf-c4.png'),
    require('../../assets/map-markers/own-leaf-c5.png'),
    require('../../assets/map-markers/own-leaf-c6.png'),
    require('../../assets/map-markers/own-leaf-c7.png'),
    require('../../assets/map-markers/own-leaf-c8.png'),
    require('../../assets/map-markers/own-leaf-c9.png'),
  ],
  mushroom: [
    require('../../assets/map-markers/own-mushroom-c0.png'),
    require('../../assets/map-markers/own-mushroom-c1.png'),
    require('../../assets/map-markers/own-mushroom-c2.png'),
    require('../../assets/map-markers/own-mushroom-c3.png'),
    require('../../assets/map-markers/own-mushroom-c4.png'),
    require('../../assets/map-markers/own-mushroom-c5.png'),
    require('../../assets/map-markers/own-mushroom-c6.png'),
    require('../../assets/map-markers/own-mushroom-c7.png'),
    require('../../assets/map-markers/own-mushroom-c8.png'),
    require('../../assets/map-markers/own-mushroom-c9.png'),
  ],
  spade: [
    require('../../assets/map-markers/own-spade-c0.png'),
    require('../../assets/map-markers/own-spade-c1.png'),
    require('../../assets/map-markers/own-spade-c2.png'),
    require('../../assets/map-markers/own-spade-c3.png'),
    require('../../assets/map-markers/own-spade-c4.png'),
    require('../../assets/map-markers/own-spade-c5.png'),
    require('../../assets/map-markers/own-spade-c6.png'),
    require('../../assets/map-markers/own-spade-c7.png'),
    require('../../assets/map-markers/own-spade-c8.png'),
    require('../../assets/map-markers/own-spade-c9.png'),
  ],
  star: [
    require('../../assets/map-markers/own-star-c0.png'),
    require('../../assets/map-markers/own-star-c1.png'),
    require('../../assets/map-markers/own-star-c2.png'),
    require('../../assets/map-markers/own-star-c3.png'),
    require('../../assets/map-markers/own-star-c4.png'),
    require('../../assets/map-markers/own-star-c5.png'),
    require('../../assets/map-markers/own-star-c6.png'),
    require('../../assets/map-markers/own-star-c7.png'),
    require('../../assets/map-markers/own-star-c8.png'),
    require('../../assets/map-markers/own-star-c9.png'),
  ],
  train: [
    require('../../assets/map-markers/own-train-c0.png'),
    require('../../assets/map-markers/own-train-c1.png'),
    require('../../assets/map-markers/own-train-c2.png'),
    require('../../assets/map-markers/own-train-c3.png'),
    require('../../assets/map-markers/own-train-c4.png'),
    require('../../assets/map-markers/own-train-c5.png'),
    require('../../assets/map-markers/own-train-c6.png'),
    require('../../assets/map-markers/own-train-c7.png'),
    require('../../assets/map-markers/own-train-c8.png'),
    require('../../assets/map-markers/own-train-c9.png'),
  ],
  tree: [
    require('../../assets/map-markers/own-tree-c0.png'),
    require('../../assets/map-markers/own-tree-c1.png'),
    require('../../assets/map-markers/own-tree-c2.png'),
    require('../../assets/map-markers/own-tree-c3.png'),
    require('../../assets/map-markers/own-tree-c4.png'),
    require('../../assets/map-markers/own-tree-c5.png'),
    require('../../assets/map-markers/own-tree-c6.png'),
    require('../../assets/map-markers/own-tree-c7.png'),
    require('../../assets/map-markers/own-tree-c8.png'),
    require('../../assets/map-markers/own-tree-c9.png'),
  ],
};

export const CLUSTER_MARKER_IMAGE = require('../../assets/map-markers/cluster.png');

export function mapMarkerImage(symbol?: string | null, color?: string | null, own = false) {
  const colorIndex = Math.max(
    0,
    SYMBOL_COLORS.findIndex((item) => item.toLowerCase() === color?.toLowerCase()),
  );
  const images = own ? ownMarkerImages : markerImages;
  return (images[symbol ?? 'hat'] ?? images.hat)[colorIndex] ?? images.hat[0];
}
