import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#f6f7f9' },
  centerScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    padding: 24,
    backgroundColor: '#f6f7f9',
  },
  auth: { flexGrow: 1, justifyContent: 'center', gap: 14, padding: 24 },
  brand: { fontSize: 34, fontWeight: '800', color: '#14314f' },
  lead: { fontSize: 16, lineHeight: 23, color: '#3f4b5f' },
  topbar: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#dbe3ec',
    backgroundColor: '#ffffff',
    zIndex: 10,
  },
  topbarBrand: {
    width: 92,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  topbarIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#1565c0',
  },
  topbarTitle: {
    color: '#14314f',
    fontSize: 14,
    fontWeight: '900',
  },
  topbarGroup: {
    flex: 1,
    textAlign: 'center',
    color: '#253044',
    fontWeight: '800',
    paddingHorizontal: 8,
  },
  topbarUserWrap: {
    width: 92,
    alignItems: 'flex-end',
  },
  topbarUserButton: {
    maxWidth: 92,
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  topbarUserText: {
    color: '#1565c0',
    fontWeight: '800',
  },
  topbarMenu: {
    position: 'absolute',
    right: 0,
    top: 42,
    minWidth: 130,
    borderWidth: 1,
    borderColor: '#d7dee8',
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  topbarMenuItem: {
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#edf1f5',
  },
  topbarMenuText: {
    color: '#253044',
    fontWeight: '800',
  },
  topbarMenuDangerText: {
    color: '#b42318',
    fontWeight: '800',
  },
  mapWithNotice: { position: 'relative' },
  mapWrap: { height: 285, backgroundColor: '#dde6ef' },
  map: { ...StyleSheet.absoluteFillObject },
  mapSendBackdrop: {
    flex: 1,
    justifyContent: 'center',
    padding: 18,
    backgroundColor: 'rgba(17,24,39,0.24)',
  },
  mapSendPopup: {
    gap: 10,
    padding: 12,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d7dee8',
  },
  mapSendHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  mapSendTitle: { color: '#182536', fontSize: 16, fontWeight: '900' },
  mapSendActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  mapSendIconButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#eef1f5',
  },
  mapSendSubmit: { backgroundColor: '#1565c0' },
  sentLocationPopup: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 12,
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderWidth: 1,
    borderColor: '#d7dee8',
  },
  sentLocationPopupText: { flex: 1, color: '#182536', fontSize: 13, fontWeight: '700' },
  sentLocationClose: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#eef1f5',
  },
  mapOverlay: {
    position: 'absolute',
    left: 12,
    right: 12,
    top: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  mapTitle: { fontSize: 15, fontWeight: '800', color: '#112033' },
  mapSubtitle: { color: '#516070', marginTop: 2 },
  callout: { minWidth: 190, gap: 3 },
  calloutTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 2 },
  calloutTitle: { fontWeight: '800', marginBottom: 2 },
  clusterCallout: { minWidth: 210, gap: 7 },
  clusterCalloutRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  clusterCalloutText: { color: '#253044' },
  noticeArea: { paddingHorizontal: 12, paddingTop: 8, gap: 6 },
  noticeOverlay: {
    position: 'absolute',
    top: 10,
    left: 12,
    right: 12,
    zIndex: 6,
    gap: 6,
  },
  notice: {
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#fff4d6',
    borderWidth: 1,
    borderColor: '#f2c94c',
  },
  noticeSuccess: { backgroundColor: '#e7f8ef', borderColor: '#45b36b' },
  noticeText: { color: '#253044' },
  tabs: {
    flexDirection: 'row',
    paddingHorizontal: 22,
    paddingTop: 7,
    paddingBottom: 7,
  },
  tab: {
    flex: 1,
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#cfd8e3',
    backgroundColor: '#e5e9ef',
  },
  tabFirst: {
    borderTopLeftRadius: 14,
    borderBottomLeftRadius: 14,
  },
  tabMiddle: {
    marginLeft: -1,
  },
  tabLast: {
    marginLeft: -1,
    borderTopRightRadius: 14,
    borderBottomRightRadius: 14,
  },
  tabActive: { backgroundColor: '#006d77', borderColor: '#006d77', zIndex: 1 },
  tabText: { fontSize: 13, fontWeight: '800', color: '#111827' },
  tabTextActive: { color: '#ffffff' },
  dot: {
    position: 'absolute',
    top: 6,
    right: 10,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ef4444',
  },
  content: { flex: 1 },
  contentInner: { padding: 12, paddingBottom: 28 },
  chatScreen: { flex: 1 },
  chatList: { flex: 1, backgroundColor: '#eef1f4' },
  chatListContent: {
    flexGrow: 1,
    justifyContent: 'flex-end',
    padding: 12,
    paddingBottom: 8,
  },
  chatComposer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: '#dbe3ec',
    backgroundColor: '#ffffff',
  },
  composerModeButton: {
    width: 58,
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#e5e9ef',
  },
  composerModeText: { color: '#344154', fontSize: 11, fontWeight: '900' },
  composerFields: { flex: 1, gap: 6 },
  composerInput: {
    minHeight: 38,
    maxHeight: 58,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 12,
    lineHeight: 16,
    textAlignVertical: 'top',
  },
  composerQuestionInput: {
    minHeight: 38,
    maxHeight: 38,
  },
  composerIconButton: {
    width: 46,
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#1565c0',
  },
  stack: { gap: 12 },
  section: {
    gap: 10,
    padding: 14,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e7ee',
  },
  sectionHeader: {
    minHeight: 26,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionTitle: { fontSize: 18, fontWeight: '800', color: '#15263b' },
  sectionToggle: { color: '#1565c0', fontSize: 20, fontWeight: '900' },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: '#cfd8e3',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#ffffff',
    color: '#111827',
  },
  inputRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  inputRowField: { flex: 1 },
  textArea: { minHeight: 82, textAlignVertical: 'top' },
  primaryButton: {
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#1565c0',
  },
  primaryButtonText: { color: '#ffffff', fontWeight: '800' },
  secondaryButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1565c0',
    backgroundColor: '#eef6ff',
  },
  secondaryButtonText: { color: '#124f96', fontWeight: '800' },
  dangerButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#b42318',
  },
  dangerButtonText: { color: '#ffffff', fontWeight: '800' },
  textButton: { alignSelf: 'flex-start', paddingVertical: 8 },
  textButtonText: { color: '#1565c0', fontWeight: '800' },
  disabled: { opacity: 0.55 },
  muted: { color: '#667085', lineHeight: 20 },
  warning: { color: '#b42318', fontWeight: '700' },
  label: { color: '#253044', fontWeight: '700' },
  paragraph: { color: '#344054', lineHeight: 21 },
  infoBox: { gap: 6, padding: 12, borderRadius: 8, backgroundColor: '#f2f6fa' },
  infoTitle: { fontWeight: '800', color: '#182536' },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  groupChip: {
    minWidth: 128,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#eef1f5',
    borderWidth: 1,
    borderColor: '#d7dee8',
  },
  groupChipActive: { borderColor: '#1565c0', backgroundColor: '#e4f1ff' },
  groupChipTitle: { fontWeight: '800', color: '#243244' },
  groupChipMeta: { marginTop: 2, color: '#667085' },
  groupStatusRow: {
    minHeight: 34,
    justifyContent: 'center',
  },
  groupStatusText: {
    color: '#253044',
    fontWeight: '800',
  },
  groupStatusStrong: {
    fontWeight: '900',
  },
  groupSelectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  codeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  codeButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: '#e4f1ff',
    borderWidth: 1,
    borderColor: '#b8dafb',
  },
  codeButtonText: {
    color: '#124f96',
    fontWeight: '900',
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  checkboxRow: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 4,
  },
  checkbox: {
    width: 21,
    height: 21,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#98a2b3',
    backgroundColor: '#ffffff',
  },
  checkboxChecked: {
    borderColor: '#1565c0',
    backgroundColor: '#1565c0',
  },
  checkboxMark: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
    lineHeight: 18,
  },
  profileButtonRow: {
    alignItems: 'flex-end',
    gap: 7,
    marginTop: 4,
  },
  profileButton: {
    width: 188,
    minHeight: 36,
    paddingHorizontal: 12,
  },
  preferenceDivider: {
    height: 1,
    marginVertical: 3,
    backgroundColor: '#e2e7ee',
  },
  preferenceStatus: {
    marginTop: -4,
    color: '#667085',
    fontSize: 12,
    lineHeight: 17,
  },
  preferenceStatusActive: {
    color: '#0f7a47',
  },
  toggle: {
    minWidth: 62,
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#d0d5dd',
  },
  toggleOn: { backgroundColor: '#34a853' },
  toggleText: { color: '#ffffff', fontWeight: '800' },
  memberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingVertical: 2,
  },
  symbol: { fontSize: 20 },
  memberMain: { flex: 1 },
  memberLine: { color: '#1f2937' },
  memberName: { fontWeight: '800', color: '#1f2937' },
  memberMeta: { color: '#667085', fontWeight: '400' },
  memberActions: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  smallButton: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 8, backgroundColor: '#e9f2ff' },
  smallDanger: { backgroundColor: '#ffe8e5' },
  smallButtonText: { color: '#124f96', fontWeight: '800', fontSize: 12 },
  smallDangerText: { color: '#b42318' },
  smallIconButton: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#ffffff',
  },
  smallIconSuccess: {},
  smallIconDanger: {},
  drawnIcon: {
    position: 'relative',
    width: 18,
    height: 18,
  },
  drawnCloseLine: {
    position: 'absolute',
    left: 2,
    top: 8,
    width: 14,
    height: 3,
    borderRadius: 2,
  },
  drawnCloseLineFirst: {
    transform: [{ rotate: '45deg' }],
  },
  drawnCloseLineSecond: {
    transform: [{ rotate: '-45deg' }],
  },
  drawnCheckShort: {
    position: 'absolute',
    left: 2,
    top: 9,
    width: 7,
    height: 3,
    borderRadius: 2,
    transform: [{ rotate: '45deg' }],
  },
  drawnCheckLong: {
    position: 'absolute',
    left: 6,
    top: 7,
    width: 12,
    height: 3,
    borderRadius: 2,
    transform: [{ rotate: '-45deg' }],
  },
  segment: { flexDirection: 'row', gap: 8 },
  segmentButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
    borderRadius: 8,
    backgroundColor: '#e5e9ef',
  },
  segmentButtonActive: { backgroundColor: '#14314f' },
  segmentText: { color: '#344154', fontWeight: '800' },
  segmentTextActive: { color: '#ffffff' },
  message: {
    alignSelf: 'flex-start',
    maxWidth: '86%',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    marginBottom: 5,
  },
  messageOwn: { alignSelf: 'flex-end', backgroundColor: '#f3ead7' },
  chatMessageRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 7 },
  chatMessageSymbolWrap: {
    position: 'relative',
    width: 28,
    minHeight: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatMessageSymbol: { width: 28, minHeight: 26, alignItems: 'center', justifyContent: 'center' },
  chatMetaPopup: {
    position: 'absolute',
    left: 0,
    bottom: 24,
    zIndex: 20,
    minWidth: 84,
    maxWidth: 260,
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 7,
    backgroundColor: '#182536',
  },
  chatMetaPopupText: { color: '#ffffff', fontSize: 10, fontWeight: '700' },
  messageMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  messageMeta: { color: '#667085', fontSize: 12, fontWeight: '700' },
  messageText: { flexShrink: 1, color: '#1f2937', fontSize: 13, lineHeight: 18 },
  question: {
    alignSelf: 'flex-start',
    maxWidth: '90%',
    gap: 3,
    padding: 6,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    marginBottom: 5,
  },
  questionOwn: { alignSelf: 'flex-end', backgroundColor: '#f3ead7' },
  questionTitle: { flexShrink: 1, fontSize: 14, fontWeight: '800', color: '#182536' },
  option: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 25,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 7,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#ead7a7',
  },
  optionSelected: { borderColor: '#1565c0', backgroundColor: '#e9f2ff' },
  optionText: { color: '#182536', fontSize: 13, fontWeight: '700' },
  optionCount: { color: '#1565c0', fontSize: 13, fontWeight: '900' },
  symbolChoice: {
    width: 56,
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#eef1f5',
    borderWidth: 1,
    borderColor: '#d7dee8',
  },
  symbolChoiceActive: { borderColor: '#1565c0', backgroundColor: '#e4f1ff' },
  colorWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  swatch: { width: 34, height: 34, borderRadius: 17, borderWidth: 2, borderColor: '#ffffff' },
  swatchActive: { borderColor: '#111827' },
  preferenceRow: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  preferenceLabel: {
    width: 104,
    color: '#253044',
    fontWeight: '700',
  },
  segmentedControl: {
    flex: 1,
    minHeight: 38,
    flexDirection: 'row',
    padding: 5,
    borderRadius: 22,
    backgroundColor: '#e5e9ef',
  },
  segmentedButton: {
    flex: 1,
    minWidth: 0,
    minHeight: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    paddingHorizontal: 6,
  },
  segmentedButtonActive: {
    backgroundColor: '#006d77',
  },
  segmentedText: {
    color: '#344154',
    fontSize: 10,
    fontWeight: '800',
  },
  segmentedTextActive: {
    color: '#ffffff',
  },
  preferenceDropdown: {
    flex: 1,
  },
  empty: { padding: 18, borderRadius: 8, backgroundColor: '#ffffff' },
  dropdownBlock: {
    gap: 6,
  },
  dropdownButton: {
    flex: 1,
    minHeight: 46,
    borderWidth: 1,
    borderColor: '#cfd8e3',
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dropdownButtonText: {
    color: '#182536',
    fontWeight: '800',
  },
  dropdownCaret: {
    color: '#667085',
    fontWeight: '900',
  },
  dropdownMenu: {
    borderWidth: 1,
    borderColor: '#d7dee8',
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
  },
  dropdownOption: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#edf1f5',
  },
  dropdownOptionActive: {
    backgroundColor: '#e4f1ff',
  },
  dropdownOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  dropdownOptionTitle: {
    flex: 1,
    color: '#243244',
    fontWeight: '800',
  },
  dropdownOptionMeta: {
    color: '#667085',
  },
  adminRoleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
  },
  roleButton: {
    minWidth: 112,
    paddingHorizontal: 10,
  },
  mapUploadFileText: {
    color: '#667085',
    fontWeight: '400',
  },
});
